### PR TITLE
Feature/namespaces logging

### PR DESCRIPTION
**Pull request by haf**
I put it all out of the global NS (avoid polluting that) and revamped logging a bit, with the new [Logary Facade](https://github.com/logary/logary/#using-logary-in-a-library).

I hope this is acceptable. It's a major-version change, btw.

### CODE REVIEW

**Comment by haf** [comment]
Ping

**Comment by haf** [comment]
Gentle ping

**Comment by haf** [comment]
Are you still there @mausch ?

**Comment by haf** [comment]
Monthly ping

**Comment by haf** [comment]
PIng

**Comment by wallymathieu** [comment]
Is there really a need for this much logging infrastructure in a project that essentially only needs to have a `logDebug : string->unit` ?

**Comment by haf** [comment]
@wallymathieu I think that's an oversimplification. To have all SQL, all parameters, etc etc, logged as untyped text values will be making it harder for you to debug it. But this PR is out of date, and I'm not using FsSQL any more. I'll release what I've built when I build it.

**Comment by wallymathieu** [comment]
Aaa, so that's what you intended, I think that makes it clearer what you want then.

**Comment by haf** [comment]
Yeah, this PR would have formed the basis for e.g. performance tuning FsSQL or integrating it with tracing.

**Pull request closed without merging**
